const INPUTS = [
  null,
  DAY1,
  DAY2,
  DAY3,
  DAY4,
  DAY5,
  DAY6,
  DAY7,
  DAY8,
  DAY9,
  DAY10,
  DAY11,
  DAY12,
  DAY13,
  DAY14,
  DAY15,
  DAY16,
  DAY17,
  DAY18,
  DAY19,
  DAY20,
  DAY21,
  DAY22,
  DAY23,
  DAY24,
  DAY25,
];

// Which function to run to display the answer to a given puzzle
// Key: {day}-{puzzle}
// The function is passed one parameter, INPUT[day]
// If the answer function requires other parameters, write an anonymous function that takes input
// i.e. (input) => fn(input, extraParam)
const ANSWERS = {
  "1-1": () => "incomplete",
  "1-2": () => "incomplete",
  "2-1": () => "incomplete",
  "2-2": () => "incomplete",
  "3-1": () => "incomplete",
  "3-2": () => "incomplete",
  "4-1": () => "incomplete",
  "4-2": () => "incomplete",
  "5-1": () => "incomplete",
  "5-2": () => "incomplete",
  "6-1": () => "incomplete",
  "6-2": () => "incomplete",
  "7-1": () => "incomplete",
  "7-2": () => "incomplete",
  "8-1": () => "incomplete",
  "8-2": () => "incomplete",
  "9-1": () => "incomplete",
  "9-2": () => "incomplete",
  "10-1": () => "incomplete",
  "10-2": () => "incomplete",
  "11-1": () => "incomplete",
  "11-2": () => "incomplete",
  "12-1": () => "incomplete",
  "12-2": () => "incomplete",
  "13-1": () => "incomplete",
  "13-2": () => "incomplete",
  "14-1": () => "incomplete",
  "14-2": () => "incomplete",
  "15-1": () => "incomplete",
  "15-2": () => "incomplete",
  "16-1": () => "incomplete",
  "16-2": () => "incomplete",
  "17-1": () => "incomplete",
  "17-2": () => "incomplete",
  "18-1": () => "incomplete",
  "18-2": () => "incomplete",
  "19-1": () => "incomplete",
  "19-2": () => "incomplete",
  "20-1": () => "incomplete",
  "20-2": () => "incomplete",
  "21-1": () => "incomplete",
  "21-2": () => "incomplete",
  "22-1": () => "incomplete",
  "22-2": () => "incomplete",
  "23-1": () => "incomplete",
  "23-2": () => "incomplete",
  "24-1": () => "incomplete",
  "24-2": () => "incomplete",
  "25-1": () => "incomplete",
  "25-2": () => "incomplete",
};